name: tagged-release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  gh_tagged_release:
    runs-on: "ubuntu-22.04"

    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
        id: automatic_releases

# vim:ts=2:sw=2:et
