name: Test

on:
  pull_request:
    paths-ignore:
      - ".github/workflows/docs-build.yml"
      - "docs/**"
  push:
    paths-ignore:
      - ".github/workflows/docs-build.yml"
      - "docs/**"
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04
    name: Python ${{ matrix.python }}
    strategy:
      matrix:
        python:
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: pip
      - name: Install dependencies (pip)
        run: python -m pip install -r requirements.txt -r testing-requirements.txt
      - name: Test
        run: make test

# vim:ts=2:sw=2:et
